install: true

script:
- cd webapp
- mvn clean package -DskipTests
- cd ..

after_success:
- mkdir codedeploy_artifact
- cp infrastructure/aws/codedeploy/*.sh .
- cp infrastructure/aws/codedeploy/*.yml .
- zip -r csye6225-web-app-${TRAVIS_JOB_NUMBER}.zip webapp/target/demo-0.0.1-SNAPSHOT.war *.sh *.yml
- mv csye6225-web-app-${TRAVIS_JOB_NUMBER}.zip codedeploy_artifact/

deploy:
- provider: s3
  local_dir: codedeploy_artifact
  bucket: $code_deploy_s3_bucket
  region: us-east-1
  skip_cleanup: true
  access_key_id: $travis_access_key_id
  secret_access_key: $travis_secret_access_key

- provider: codedeploy
  access_key_id: $travis_access_key_id
  bucket: $code_deploy_s3_bucket
  key: csye6225-web-app-${TRAVIS_JOB_NUMBER}.zip
  bundle_type: zip
  application: myWebapp
  deployment_group: myWebapp
  region: us-east-1
  secret_access_key: $travis_secret_access_key
  wait-until-deployed: true
